from pathlib import Path

p = Path('index.html')
html = p.read_text(encoding='utf-8')
html = html.replace("const APP_VERSION = '2.9.3';", "const APP_VERSION = '2.9.4';")
old = '''        <p class="hero-copy">Maarif Öğretmen Akademisi öncesinde ve sonrasında öğretmenlik eğilimlerini görünür kılan, eğlenceli ve öğretici 30 adımlık gelişim deneyimi.</p>\n        <div class="hero-slogan"><b>30 Soru</b> • 15 Saniye • Kendini Keşfet • Sınıfını Yeniden Tasarla</div>\n        <div class="notice" style="margin-top:20px"><strong>Bu bir sınav değil.</strong> Öğretmenlik pratiğinin bugünkü fotoğrafı.</div>'''
new = '''        <p class="hero-copy">Maarif Öğretmen Akademisi öncesinde ve sonrasında öğretmenlik eğilimlerini görünür kılan, güçlü alanları ve gelişim fırsatlarını ortaya çıkaran 30 adımlık gelişim deneyimi.</p>\n\n        <div class="hero-info-grid">\n          <div class="hero-info-card">\n            <div class="hero-info-title">${uiIcon('radar')}<strong>Maarif Radarı Nedir?</strong></div>\n            <p>Öğretmenin 6 gelişim alanındaki pedagojik reflekslerini analiz eder; yalnızca skor değil, <b>eğilim, güçlü yön ve gelişim önceliği</b> gösterir.</p>\n          </div>\n          <div class="hero-info-card academy">\n            <div class="hero-info-title">${uiIcon('sprout')}<strong>Visiteen Maarif Akademisi Ne Değer Sağlar?</strong></div>\n            <p>Radar sonucunu eğitime dönüştürür; öğretmenin gelişim ihtiyacını belirler ve <b>öğrenme → uygulama → üretim → gelişim</b> sürecini yapılandırır.</p>\n          </div>\n        </div>\n\n        <div class="hero-slogan"><b>30 Soru</b> • 15 Saniye • Kendini Keşfet • Gelişim Alanını Gör</div>\n        <div class="notice" style="margin-top:20px"><strong>Bu bir sınav değil.</strong> Öğretmenlik pratiğinizin bugünkü fotoğrafı ve gelişim yolculuğunuzun başlangıç noktası.</div>'''
if old not in html:
    raise SystemExit('Target home block not found')
html = html.replace(old, new, 1)
css = '''\n/* V2.9.4 • Ana ekran açıklayıcı bilgi kartları */\n.hero-info-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:20px}\n.hero-info-card{position:relative;z-index:2;padding:16px 17px;border-radius:18px;background:linear-gradient(145deg,rgba(91,44,255,.055),rgba(15,67,203,.035));border:1px solid rgba(91,44,255,.13)}\n.hero-info-card.academy{background:linear-gradient(145deg,rgba(25,213,193,.085),rgba(91,44,255,.045));border-color:rgba(25,190,175,.18)}\n.hero-info-title{display:flex;align-items:center;gap:8px;color:#4F2AE8;font-size:13px;line-height:1.3}\n.hero-info-card.academy .hero-info-title{color:#087F78}\n.hero-info-title .ui-icon{width:18px;height:18px;flex:0 0 auto}\n.hero-info-card p{margin:8px 0 0;color:#586582;font-size:12.5px;line-height:1.52}\n.hero-info-card p b{color:#2E3E78}\n@media(max-width:720px){.hero-info-grid{grid-template-columns:1fr}.hero-info-card{padding:14px 15px}}\n'''
html = html.replace('</style>', css + '\n</style>', 1)
p.write_text(html, encoding='utf-8')
print('V2.9.4 home update applied')
