from pathlib import Path

p=Path('index.html')
html=p.read_text(encoding='utf-8')
html=html.replace("const APP_VERSION = '2.9.4';", "const APP_VERSION = '2.9.5';")
old='''      <div class="glass-card feature-card">\n        <div><div class="feature-badge">${uiIcon('compass')}</div><h2>Skordan fazlası</h2><p>Her cevap; pedagojik refleks, eğilim ve gelişim göstergesi olarak yorumlanır. Sonuçta 6 boyutlu radar ve saklanabilir gelişim PDF’i oluşur.</p></div>\n        <div class="mini-grid"><div class="mini-stat"><strong>6</strong><span>Yetkinlik alanı</span></div><div class="mini-stat"><strong>30</strong><span>Ölçülen refleks</span></div><div class="mini-stat"><strong>6</strong><span>Farkındalık kartı</span></div><div class="mini-stat"><strong>Ön/Son</strong><span>Eğitim etki karşılaştırması</span></div></div>\n      </div>'''
new='''      <div class="glass-card feature-card feature-card-enhanced">\n        <div>\n          <div class="feature-badge">${uiIcon('compass')}</div>\n          <h2>Skordan fazlası</h2>\n          <p>Her cevap; pedagojik refleks, eğilim ve gelişim göstergesi olarak yorumlanır. Sonuçta 6 boyutlu gelişim profili, kişisel gelişim karnesi ve eğitim öncesi–sonrası karşılaştırma oluşur.</p>\n          <div class="radar-journey">\n            <div class="radar-journey-head">Radardan Gelişime</div>\n            <div class="radar-journey-step"><span class="radar-journey-num">01</span><div><strong>Kendini Gör</strong><p>Pedagojik reflekslerini, güçlü alanlarını ve gelişim eğilimlerini keşfet.</p></div></div>\n            <div class="radar-journey-step"><span class="radar-journey-num">02</span><div><strong>Gelişim Alanını Belirle</strong><p>6 yetkinlik alanı içinde hangi becerilere öncelik vermen gerektiğini gör.</p></div></div>\n            <div class="radar-journey-step"><span class="radar-journey-num">03</span><div><strong>Akademide Geliştir</strong><p>Radar sonucunu Maarif Akademisi eğitimleri, uygulamalar ve atölye üretimleriyle gelişime dönüştür.</p></div></div>\n          </div>\n        </div>\n        <div class="mini-grid"><div class="mini-stat"><strong>6</strong><span>Yetkinlik alanı</span></div><div class="mini-stat"><strong>30</strong><span>Ölçülen refleks</span></div><div class="mini-stat"><strong>6</strong><span>Farkındalık kartı</span></div><div class="mini-stat"><strong>Ön/Son</strong><span>Eğitim etki karşılaştırması</span></div></div>\n      </div>'''
if old not in html:
    raise SystemExit('Skordan fazlasi target block not found')
html=html.replace(old,new,1)
css='''\n/* V2.9.5 • Skordan fazlası / Radardan Gelişime */\n.feature-card-enhanced{overflow:hidden}\n.feature-card-enhanced>div:first-child{min-height:0}\n.feature-card-enhanced>div:first-child>p{margin-bottom:12px}\n.radar-journey{margin-top:12px;padding:12px 14px;border-radius:17px;background:linear-gradient(145deg,rgba(91,44,255,.05),rgba(25,213,193,.055));border:1px solid rgba(91,44,255,.11)}\n.radar-journey-head{margin-bottom:7px;color:#4F2AE8;font-size:12.5px;font-weight:950}\n.radar-journey-step{display:grid;grid-template-columns:30px 1fr;gap:9px;align-items:start;padding:7px 0;border-top:1px dashed rgba(91,44,255,.12)}\n.radar-journey-step:first-of-type{border-top:0;padding-top:3px}\n.radar-journey-num{width:28px;height:28px;border-radius:9px;display:grid;place-items:center;background:linear-gradient(135deg,#0F43CB,#6B2CF5);color:#fff;font-size:9.5px;font-weight:950}\n.radar-journey-step strong{display:block;color:#173B98;font-size:11.5px;line-height:1.2}\n.radar-journey-step p{margin:3px 0 0;color:#6C7790;font-size:10.3px;line-height:1.32}\n.feature-card-enhanced .mini-grid{margin-top:12px}\n.feature-card-enhanced .mini-stat{padding:10px 12px}\n.feature-card-enhanced .mini-stat strong{font-size:18px}\n.feature-card-enhanced .mini-stat span{font-size:10.2px}\n@media(max-width:720px){.radar-journey{padding:12px}.radar-journey-step{grid-template-columns:28px 1fr;gap:8px}.radar-journey-num{width:26px;height:26px}}\n'''
html=html.replace('</style>',css+'\n</style>',1)
p.write_text(html,encoding='utf-8')
print('V2.9.5 applied')
